- name: Install ZooKeeper Packages
  yum: name={{ item }} state=present
  with_items:
    - zookeeper
    - jdk

- name: Apply zookeeper.cfg template
  template: src=etc/zookeeper/zoo.cfg.j2 dest=/etc/zookeeper/zoo.cfg

- name: Apply my.id template
  template: src=var/lib/zookeeper/myid.j2 dest=/var/lib/zookeeper/myid
  notify: restart zookeeper

- name: Start ZooKeeper
  service: name=zookeeper state=started enabled=yes
