---
- name: Install Redis Package
  yum: name=redis state=present

- debug:
    msg: "Master would be... {{ cluster_master_address }}"

- name: Apply redis.conf master template
  template: src=etc/redis.conf.j2 dest=/etc/redis.conf
  notify: restart redis
  when: cluster_master_address == ansible_default_ipv4.address

- name: Apply redis.conf slave template
  template: src=etc/redis-slave.conf.j2 dest=/etc/redis.conf
  notify: restart redis
  when: cluster_master_address != ansible_default_ipv4.address

- meta: flush_handlers

- name: Wait for redis to be up
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: 6379
    delay: 5
    timeout: 60
