---
- debug:
    msg: "Master would be... {{ cluster_master_address }}"

- name: Apply redis-sentinel.conf template
  template: src=redis-sentinel.conf.j2 dest=/etc/redis-sentinel.conf
  notify: restart redis sentinel
