---
- hosts: apis
  become: yes
  vars:
    abiquo_profile: server
    abiquo_rabbitmq_addresses: "{{ groups['datanodes']|join(':5672,') }}"
    abiquo_install_services: false
    abiquo_install_frontend: false

  roles:
    - common
    - abiquo
