---
- hosts: datanodes
  become: yes
  roles:
    - common

- hosts: datanodes[0]
  become: yes
  vars:
    rabbitmq_erlang_cookie: OIZEBMCJICBLKMOMYJUX
    cluster_master_address: "{{ ansible_default_ipv4.address }}"
    mariadb_config:
      galera:
        binlog_format: ROW
        default-storage-engine: innodb
        innodb_autoinc_lock_mode: 2
        bind-address: 0.0.0.0
        wsrep_on: ON
        wsrep_provider: /usr/lib64/galera/libgalera_smm.so
        wsrep_cluster_address: "gcomm://{{ hostvars[groups['datanodes']|join(',') }}"
        wsrep_cluster_name: paasenvcluster
        # wsrep_sst_method=rsync
        wsrep_node_address: "{{ ansible_default_ipv4.address }}"
        wsrep_node_name: "{{ ansible_hostname }}"

  roles:
    - mariadb
    - rabbitmq
    - zookeeper
    - redis
    - redis-sentinel

  tasks:
    - name: Add user abiquo
      rabbitmq_user:
        name: abiquo
        force: yes
        password: abiquo
        vhost: /
        read_priv: .*
        write_priv: .*
        configure_priv: .*
        state: present
        tags: administrator
    - name: Remove user guest
      rabbitmq_user:
        name: guest
        force: yes
        state: absent

- hosts: datanodes[1:]
  become: true
  vars:
    rabbitmq_erlang_cookie: OIZEBMCJICBLKMOMYJUX
    cluster_master_address: "{{ hostvars[groups['datanodes'][0]]['ansible_default_ipv4']['address'] }}"

  roles:
    - rabbitmq
    - zookeeper
    - redis
    - redis-sentinel

  tasks:
    - name: stop rabbitmq app
      shell: rabbitmqctl stop_app
    - name: join rabbitmq cluster
      shell: rabbitmqctl join_cluster rabbit@{{ hostvars[groups['datanodes'][0]]['ansible_hostname'] }}
    - name: start rabbitmq app
      shell: rabbitmqctl start_app
