---
- hosts: datanodes[0]
  become: true
  vars:
    rabbitmq_erlang_cookie: OIZEBMCJICBLKMOMYJUX
  roles:
    - common
    - rabbitmq
    - zookeeper
    - redis

  tasks:
    - name: Add user abiquo
      rabbitmq_user:
        name: abiquo
        force: yes
        password: abiquo
        vhost: /
        read_priv: .*
        write_priv: .*
        configure_priv: .*
        state: present
        tags: administrator
    - name: Remove user guest
      rabbitmq_user:
        name: guest
        force: yes
        state: absent

- hosts: datanodes[1:]
  become: true
  vars:
    rabbitmq_erlang_cookie: OIZEBMCJICBLKMOMYJUX
  roles:
    - common
    - rabbitmq
    - zookeeper
    - redis-slave

  tasks:
    - set_fact:
        cluster_master_address: "{{ hostvars[groups['datanodes'][0]]['ansible_default_ipv4']['address'] }}"
    - name: stop rabbitmq app
      shell: rabbitmqctl stop_app
    - name: join rabbitmq cluster
      shell: rabbitmqctl join_cluster rabbit@{{ cluster_master_address }}
    - name: start rabbitmq app
      shell: rabbitmqctl start_app

