---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ssh_key_name: mcirauqui
    vpc_name: ansible_paas_vpc
    vpc_region: eu-central-1
    vpc_cidr: 172.16.0.0/16
    internal_networks:
      db: 172.16.20.0/24
      api_rs: 172.16.30.0/24
    data_count: 3
    data_image_id: ami-9a183671
    data_instance_type: t2.large

  tasks:
    - name: Locate VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Locate private networks
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        cidr: "{{ item.value }}"
        resource_tags:
          Name: "{{ item.key }}_subnet"
      register: internal_subnets
      with_dict: "{{ internal_networks }}"

    - name: Create Data node security group
      ec2_group:
        name: datanode
        description: Data node access SG
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            group_name: management
            rule_desc: allow all on port 22
          - proto: tcp
            ports:
              - 15672
            group_name: management
            rule_desc: RabbitMQ management
          - proto: tcp
            ports:
              - 2181
            group_name: management
            rule_desc: Zookeeper management
          - proto: tcp
            ports:
              - 3306
              - 4567
              - 4568
              - 4444
            group_name: management
            rule_desc: Galera management
          - proto: tcp
            from_port: 1
            to_port: 65535
            group_name: datanode
            rule_desc: Allow access from any other datanode

    - set_fact:
        db_net: "{{ (internal_subnets.results|selectattr('item.key', 'match', 'db')|list)[0] }}"

    - name: Deploy Data nodes VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ data_instance_type }}"
        image: "{{ data_image_id }}"
        wait: yes
        group: datanode
        vpc_subnet_id: "{{ db_net.subnet.id }}"
        region: "{{ vpc_region }}"
        exact_count: "{{ data_count }}"
        count_tag:
          type: datanode
        instance_tags:
          type: datanode
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
            delete_on_termination: yes
      register: datanodes

    - name: Address of the data nodes
      debug:
        msg: "{{ item.private_dns_name }} ({{ item.private_ip }})"
      with_items: "{{ datanodes.tagged_instances }}"

    - name: Add new instances to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: datanodes
        ansible_ssh_user: centos
        ansible_become: yes
      with_items: "{{ datanodes.tagged_instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ datanodes.tagged_instances }}"
