---
- hosts: frontends
  become: yes
  vars:
    balancer_members_list: '{{ groups["apis"] | map("regex_replace", "^(.*)$", "BalancerMember ajp://\1:8010/api") | list }}'
    balancer_m_members_list: '{{ groups["apis"] | map("regex_replace", "^(.*)$", "BalancerMember http://\1:8009/m") | list }}'
    balancer_members: "{{ balancer_members_list | join('\n') }}"
    balancer_m_members: "{{ balancer_m_members_list | join('\n') }}"
    abiquo_profile: frontend
    ui_apache_opts_raw: |
      <Proxy "balancer://api">
          {{ balancer_members }}
          ProxySet stickysession=ABQSESSIONID|abqsessionid
      </Proxy>
      <Proxy "balancer://m">
          {{ balancer_m_members }}
          ProxySet stickysession=ABQSESSIONID|abqsessionid
      </Proxy>
    ui_proxies:
      /api:
        url: balancer://api
      /m:
        url: balancer://m
      /legal:
        url: http://localhost:8009/legal

  roles:
    - common
    - abiquo
