---
- src: https://github.com/abiquo/ansible-abiquo
  name: abiquo

- src: https://github.com/devgateway/ansible-role-pacemaker
  name: devgateway.pacemaker

- src: https://github.com/ernestas-poskus/ansible-prometheus
  name: ansible-prometheus
