---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ssh_key_name: mcirauqui
    vpc_name: ansible_paas_vpc
    vpc_region: eu-central-1
    vpc_cidr: 172.16.0.0/16
    internal_networks:
      db: 172.16.20.0/24
      api_rs: 172.16.30.0/24
    data_count: 3
    data_image_id: ami-9a183671
    data_instance_type: t2.large

  tasks:
    - name: Locate VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Locate private networks
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        cidr: "{{ item.value }}"
        resource_tags:
          Name: "{{ item.key }}_subnet"
      register: internal_subnets
      with_dict: "{{ internal_networks }}"

    - set_fact:
        db_net: "{{ (internal_subnets.results|selectattr('item.key', 'match', 'db')|list)[0] }}"

    - name: Locate Data nodes VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ data_instance_type }}"
        image: "{{ data_image_id }}"
        wait: yes
        group: datanode
        vpc_subnet_id: "{{ db_net.subnet.id }}"
        region: "{{ vpc_region }}"
        exact_count: 0
        count_tag:
          type: datanode
        instance_tags:
          type: datanode
      register: datanodes

    - name: Delete Data node security group
      ec2_group:
        name: datanode
        description: Data node access SG
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        state: absent
