---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ssh_key_name: mcirauqui
    vpc_name: ansible_paas_vpc
    vpc_region: eu-central-1
    vpc_cidr: 172.16.0.0/16
    internal_networks:
      frontend: 172.16.100.0/24
      db: 172.16.20.0/24
      api_rs: 172.16.30.0/24
    api_count: 2
    api_image_id: ami-9a183671
    api_instance_type: t2.medium

  tasks:
    - name: Locate VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Locate private networks
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        cidr: "{{ item.value }}"
        resource_tags:
          Name: "{{ item.key }}_subnet"
      register: internal_subnets
      with_dict: "{{ internal_networks }}"

    - set_fact:
        api_net: "{{ (internal_subnets.results|selectattr('item.key', 'match', 'api_rs')|list)[0] }}"

    - name: Deploy API VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ api_instance_type }}"
        image: "{{ api_image_id }}"
        wait: yes
        group: apis
        vpc_subnet_id: "{{ api_net.subnet.id }}"
        region: "{{ vpc_region }}"
        exact_count: "{{ api_count }}"
        count_tag:
          type: api
        instance_tags:
          type: api
          Name: api
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
            delete_on_termination: yes
      register: apis

    - name: Address of the APIs
      debug:
        msg: "{{ item.private_dns_name }} ({{ item.private_ip }})"
      with_items: "{{ apis.tagged_instances }}"

    - name: Add new instances to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: apis
        ansible_ssh_user: centos
        ansible_become: yes
      with_items: "{{ apis.tagged_instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ apis.tagged_instances }}"
