---
- name: restart mysql
  service: name=mysql state=restarted

- name: reset mariadb pass
  block:
    - name: Install requirements
      yum: name=MySQL-python state=present

    - name: Stop MariaDB
      service: name=mysql state=stopped

    - name: Start with skip grants
      shell: nohup mysqld_safe --skip-grant-tables &

    - name: Change root pass
      mysql_db:
        name: mysql
        state: import
        target: /root/.mysql_pw
        login_user: root
        login_password: ''

    - name: Restart MariaDB
      service: name=mysql state=restarted
