---
- name: Install RabbitMQ Package
  yum: name=rabbitmq-server state=present

- name: Configure erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    mode: 0600

- name: Configure cluster partition handling
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq service

- meta: flush_handlers

- name: Wait for rabbit to be up
  wait_for:
    host: 0.0.0.0
    port: 5672
    delay: 5
    timeout: 60

- name: Configure policies for abiquo queues
  rabbitmq_policy:
    name: abiquo-ha
    pattern: abiquo.*
  args:
    tags:
      ha-mode: all

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
