- name: Install RabbitMQ Package
  yum: name=rabbitmq-server state=present

- name: Configure erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    mode: 0600

- name: Configure cluster partition handling
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq service

- meta: flush_handlers

- name: Wait for rabbit to be up
  wait_for:
    host: 0.0.0.0
    port: 5672
    delay: 5
    timeout: 60

- name: Configure policies for abiquo queues
  rabbitmq_policy:
    name: abiquo-ha
    pattern: abiquo.*
  args:
    tags:
      ha-mode: all

- name: Add user abiquo
  rabbitmq_user:
    name: abiquo
    force: yes
    password: abiquo
    vhost: /
    read_priv: .*
    write_priv: .*
    configure_priv: .*
    state: present
    tags: administrator
  when: "'services-master' in group_names"

- name: Remove user guest
  rabbitmq_user:
    name: guest
    force: yes
    state: absent
  when: "'services-master' in group_names"


- name: Get master ready
  command: /bin/true
  when: "'services-master' in group_names"
  register: master_ready

- name: stop rabbitmq app
  shell: rabbitmqctl stop_app
  when:
    - "'services-slaves' in group_names"
    - master_ready is defined

- name: join rabbitmq cluster
  shell: rabbitmqctl join_cluster rabbit@{{ hostvars[groups['services-master'][0]]['ansible_hostname'] }}
  when:
    - "'services-slaves' in group_names"
    - master_ready is defined

- name: start rabbitmq app
  shell: rabbitmqctl start_app
  when:
    - "'services-slaves' in group_names"
    - master_ready is defined
