---
- name: Generate /etc/hosts file
  template:
    src=etc/hosts.j2
    dest=/etc/hosts

- name: Create Base Repo
  yum_repository:
    name: abiquo-base
    description: Abiquo base packages
    file: abiquo-base
    baseurl: "http://mirror.abiquo.com/el7/4.2/os/x86_64"
    gpgcheck: false
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-RSA-KEY-Abiquo
    enabled: yes

- name: Install abiquo-release
  yum: name=abiquo-release-ee state=present
