---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Locate VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Locate private networks
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        cidr: "{{ item.value }}"
        resource_tags:
          Name: "{{ item.key }}_subnet"
      register: internal_subnets
      with_dict: "{{ internal_networks }}"

    - set_fact:
        fe_net: "{{ (internal_subnets.results|selectattr('item.key', 'match', 'frontend')|list)[0] }}"

    - name: Deploy FE nodes VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ fe_instance_type }}"
        image: "{{ fe_image_id }}"
        wait: yes
        group: frontend
        vpc_subnet_id: "{{ fe_net.subnet.id }}"
        region: "{{ vpc_region }}"
        exact_count: "{{ fe_count }}"
        count_tag:
          type: frontend
        instance_tags:
          type: frontend
          Name: frontend
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
            delete_on_termination: yes
      register: frontends

    - name: Address of the frontend nodes
      debug:
        msg: "{{ item.private_dns_name }} ({{ item.private_ip }})"
      with_items: "{{ frontends.tagged_instances }}"

    - name: Add new instances to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: frontends
        ansible_ssh_user: centos
        ansible_become: yes
      with_items: "{{ frontends.tagged_instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ frontends.tagged_instances }}"

    # - name: Create LB
    #   ec2_elb_lb:
    #     name: abq-fe
    #     state: present
    #     vpc_id: "{{ vpc.vpc.id }}"
    #     region: "{{ vpc_region }}"
    #     instance_ids: "{{ frontends.tagged_instances|map(attribute='id')|list }}"
    #     zones:
    #       - "{{ vpc_region }}a"
    #       - "{{ vpc_region }}b"
    #     listeners:
    #       - protocol: http
    #         load_balancer_port: 80
    #         instance_port: 80
    #         proxy_protocol: True
    #       - protocol: tcp
    #         load_balancer_port: 443
    #         instance_protocol: tcp
    #         instance_port: 443
