---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Locate VPC
      ec2_vpc_net_facts:
        filters:
          cidr: "{{ vpc_cidr }}"
          tag:Name: "{{ vpc_name }}"
        region: "{{ vpc_region }}"
      register: vpcs

    - name: Locate private networks
      ec2_vpc_subnet_facts:
        region: "{{ vpc_region }}"
        filters:
          vpc-id: "{{ vpcs.vpcs[0].vpc_id }}"
          cidr: "{{ item.value }}"
          tag:Name: "{{ item.key }}_subnet"
      with_dict: "{{ internal_networks }}"
      register: private_subnets

    - set_fact:
        api_net: "{{ (private_subnets.results|selectattr('item.key', 'match', 'api_rs')|list)[0] }}"

    - name: Deploy RS VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ rs_instance_type }}"
        image: "{{ rs_image_id }}"
        wait: yes
        group: remoteservices
        vpc_subnet_id: "{{ api_net.subnets[0].id }}"
        region: "{{ vpc_region }}"
        exact_count: "{{ rs_count }}"
        count_tag:
          type: remoteservices
        instance_tags:
          type: remoteservices
          Name: remoteservices
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
            delete_on_termination: yes
      register: rs
