---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Locate VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Locate private networks
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        cidr: "{{ item.value }}"
        resource_tags:
          Name: "{{ item.key }}_subnet"
      register: internal_subnets
      with_dict: "{{ internal_networks }}"

    - set_fact:
        fe_net: "{{ (internal_subnets.results|selectattr('item.key', 'match', 'frontend')|list)[0] }}"

    - name: Delete FE nodes VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ fe_instance_type }}"
        image: "{{ fe_image_id }}"
        wait: yes
        group: frontend
        vpc_subnet_id: "{{ fe_net.subnet.id }}"
        region: "{{ vpc_region }}"
        exact_count: 0
        count_tag:
          type: frontend
        instance_tags:
          type: frontend
          Name: frontend
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
            delete_on_termination: yes
      register: frontends
