---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Delete API VM
      ec2:
        image: "{{ api_image_id }}"
        wait: yes
        region: "{{ vpc_region }}"
        exact_count: 0
        count_tag:
          type: api
        instance_tags:
          type: api
          Name: api
