---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Delete Data nodes VM
      ec2:
        image: "{{ data_image_id }}"
        wait: yes
        region: "{{ vpc_region }}"
        exact_count: 0
        count_tag:
          type: datanode
        instance_tags:
          type: datanode
