---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Delete Monitoring nodes VM
      ec2:
        image: "{{ monitoring_image_id }}"
        wait: yes
        region: "{{ vpc_region }}"
        exact_count: 0
        count_tag:
          type: monitoring
        instance_tags:
          type: monitoring
          Name: monitoring
