---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get vars
      include_vars: vars.yml

    - name: Locate VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Locate public network
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ vpc_region }}"
        cidr: "{{ public_subnet_cidr }}"
        resource_tags:
          Name: public_subnet
      register: public_subnet

    - name: Undeploy FE nodes VM
      ec2:
        key_name: "{{ ssh_key_name }}"
        instance_type: "{{ fe_instance_type }}"
        image: "{{ fe_image_id }}"
        wait: yes
        group: frontend
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        region: "{{ vpc_region }}"
        exact_count: 0
        count_tag:
          type: frontend
        instance_tags:
          type: frontend
          Name: frontend
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
            delete_on_termination: yes
      register: frontends
